#!/bin/sh
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

pass() {
  echo "PASS: $1"
}

grep -q 'js/core.js' index.html || fail "index.html must load js/core.js"
grep -q 'js/scenes-act2.js' index.html || fail "index.html must load js/scenes-act2.js"
grep -q 'js/scenes-final.js' index.html || fail "index.html must load js/scenes-final.js"
pass "script tags exist"

core_line=$(grep -n 'js/core.js' index.html | cut -d: -f1)
world_line=$(grep -n 'js/world.js' index.html | cut -d: -f1)
act2_line=$(grep -n 'js/scenes-act2.js' index.html | cut -d: -f1)
final_line=$(grep -n 'js/scenes-final.js' index.html | cut -d: -f1)

[ "$core_line" -lt "$world_line" ] || fail "core.js must load before world.js"
[ "$world_line" -lt "$act2_line" ] || fail "world.js must load before scenes-act2.js"
[ "$act2_line" -lt "$final_line" ] || fail "scenes-act2.js must load before scenes-final.js"
pass "script order is valid"

grep -q 'k.scene("floor8"' js/scenes-act2.js || fail "floor8 scene must be registered"
grep -q 'k.onKeyPress("t"' js/dialog.js || fail "T key must open laptop"
grep -q 'moveDialogSelection' js/dialog.js || fail "dialogs must support keyboard navigation"
grep -q 'chooseDialogNumber' js/dialog.js || fail "dialogs must support number shortcuts"
grep -q 'function openLaptop' js/dialog.js || fail "laptop UI must exist"
grep -q 'saveGame();' js/dialog.js || fail "laptop must call saveGame"
pass "laptop and floor8 hooks exist"

grep -q 'function ensureGameShell' js/core.js || fail "core.js must generate the game shell"
grep -q 'id="code-terminal"' js/core.js || fail "typed code terminal must be generated by JS"
grep -q 'function createGameHUD' js/core.js || fail "game HUD must be rendered inside the canvas"
grep -q 'createGameHUD();' js/world.js || fail "room rendering must attach the in-game HUD"
grep -q 'mobileInput' js/core.js || fail "mobile input state must exist"
grep -q 'mobileInput.x' js/world.js || fail "player movement must read mobile joystick"
grep -q 'mobile-controls' styles.css || fail "mobile controls must be styled"
! grep -q 'id="inventory"' index.html || fail "inventory must not be static HTML"
! grep -q 'id="task"' index.html || fail "task panel must not be static HTML"
grep -q 'function openCodePuzzle' js/dialog.js || fail "typed code puzzle helper must exist"
grep -q 'openCodePuzzle({' js/scenes-act1.js || fail "Aigerim laptop must use typed code puzzle"
grep -q 'codePuzzleOpen' js/world.js || fail "typed code puzzle must pause player controls"
pass "typed code mini-game hooks exist"

grep -q 'function setupAct2OfficeHaunt' js/scenes-act2.js || fail "Act 2 office haunt system must exist"
grep -q 'function addGlitchMonitor' js/scenes-act2.js || fail "Act 2 glitch monitors must exist"
grep -q 'function addRepeatingEmployee' js/scenes-act2.js || fail "Act 2 repeating employees must exist"
grep -q 'act2ElevatorLieSeen' js/core.js || fail "Act 2 haunted elevator state must exist"
pass "act 2 office horror hooks exist"

grep -q 'fd7BriefingDone' js/core.js || fail "Act 0 Serik briefing state must exist"
grep -q 'const FLOOR_BRIEFING' js/scenes-act1.js || fail "Act 0 must describe all company floors"
grep -q 'function serikCompanyBriefing' js/scenes-act1.js || fail "Act 0 company briefing must exist"
grep -q 'function serikWorkBriefing' js/scenes-act1.js || fail "Act 0 work briefing must exist"
pass "act 0 onboarding briefing hooks exist"

grep -q 'const TOUR_FLOORS' js/scenes-act1.js || fail "Act 0 tour floors must exist"
grep -q 'floor11_tour' js/scenes-act1.js || fail "Act 0 elevator must include floor 11 tour"
grep -q 'floor2_tour' js/scenes-act1.js || fail "Act 0 elevator must include floor 2 tour"
grep -q 'Support' js/characters.js || fail "support sprite must exist"
grep -q 'Security' js/characters.js || fail "security sprite must exist"
pass "act 0 elevator floor tour hooks exist"

grep -q 'act0ReceptionDone' js/core.js || fail "Act 0 receptionist escort state must exist"
grep -q 'k.go("lobby")' js/cutscenes.js || fail "new game must start at reception lobby"
grep -q 'ELEVATOR_SPAWNS' js/core.js || fail "elevator spawn map must exist"
grep -q 'arriveFromElevator' js/world.js || fail "player must spawn near elevator after elevator travel"
grep -q 'dialogReadyAt' js/dialog.js || fail "dialog debounce must exist"
pass "reception, elevator spawn, and dialog debounce hooks exist"

grep -q 'act0DanaTask' js/core.js || fail "Act 0 Dana onboarding state must exist"
grep -q 'function act0DanaTalk' js/scenes-act1.js || fail "Act 0 Dana intro must exist"
grep -q 'function checkAct0DanaKnowledge' js/scenes-act1.js || fail "Act 0 NEXAI knowledge search must exist"
grep -q 'ПЕРЕГОВОРНАЯ HR' js/scenes-act1.js || fail "reception escort must use walkable HR meeting room"
pass "act 0 Dana and walkable reception flow hooks exist"

grep -q 'act0CoreTask' js/core.js || fail "Act 0 core onboarding state must exist"
grep -q 'k.scene("floor0_core"' js/scenes-act1.js || fail "Act 0 floor 0 core scene must exist"
grep -q 'act0_first_dive' js/cutscenes.js || fail "Act 0 first DANNA dive cutscene must exist"
grep -q 'core_engineer' js/characters.js || fail "core engineer sprite must exist"
pass "act 0 core and first DANNA dive hooks exist"

if command -v osascript >/dev/null 2>&1; then
  for file in js/*.js; do
    output="$(osascript -l JavaScript "$file" 2>&1 || true)"
    case "$output" in
      *SyntaxError*) fail "syntax error in $file: $output" ;;
      *) : ;;
    esac
  done
  pass "all JS files parse without SyntaxError"
else
  echo "SKIP: osascript not available for syntax parsing"
fi

echo "All tests passed."
